title: kokurata-blog
email: ''
description: >-
  SharePoint / OneDrive / Stream に関する技術メモと運用ノウハウ。
baseurl: ''
url: 'https://kokurata.github.io'
theme: jekyll-theme-primer
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:categories/:title/

# Minimal Mistakes specific settings
author:
  name: Koki Kurata
  email: ''
# Removed Minimal Mistakes specific settings because the remote theme used
# Liquid tags/plugins not available in GitHub Pages environment.
# Using the supported `jekyll-theme-primer` to ensure Builds succeed.

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single