title: "サポートエンジニアの技術ノート"
email: ''
description: >-
  すべての投稿は「現状のまま」提供され、いかなる保証もなく、権利も付与されません。
  このブログで表明された意見や見解は著者のものであり、必ずしもマイクロソフトの見解を述べたり反映したりするものではありません。
baseurl: '/kokurata-blog'
url: 'https://kokurata.github.io'
theme: jekyll-theme-primer

# 言語設定
lang: ja

# ブログ設定
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"

# プラグイン
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# マークダウン設定
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# パーマリンク設定
permalink: /blog/:title/

# 作者情報
author:
  name: Koki Kurata
  email: ''

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  author: Koki Kurata
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# 除外ファイル
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - backup_deleted/