title: kokurata-blog
email: ''
description: >-
  SharePoint / OneDrive / Stream に関する技術メモと運用ノウハウ。
baseurl: ''
url: 'https://kokurata.github.io'
remote_theme: pmarsceill/just-the-docs@v0.7.0
plugins:
  - jekyll-paginate
markdown: kramdown
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post